#database configurations

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:docmind}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  #open ai configurations
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo-key}
      chat:
        model: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
        temperature: 0.2
      embedding:
        model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}


    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        table-name: vector_store
        schema-name: public
        initialize-schema: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 50MB

#app configurations
app:
  rag:
    chunk-size: 700
    #    chunk-overlap: 100
    top-k: 5
    similarity-threshold: 0.0

  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
